service:
  name: user-api-service
  port: 3000
  tags: ['api']
consul:
  host: 106.12.173.182
  port: 8500
  check:
    protocol: http
    route: /health
    interval: 30s
    timeout: 3s
    maxRetry: 5
    retryInterval: 5s
    deregisterCriticalServiceAfter: 60m
database:
  type: postgres
  username: admin
  password: admin123456
  database: user_db
  synchronize: true
  logging: false
